import React, { useMemo, useState } from 'react';
import { Routes, Route, useLocation } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Activity, CalendarClock, FileChartColumn, Gauge, LayoutDashboard, PlugZap, SearchCheck, Settings2, ScanSearch, Plus, Play, Clock3, KeyRound, SlidersHorizontal, CircleDollarSign } from 'lucide-react';
import { mockSaas } from '@rasai/prototype-mocks';
import type { AuditSummary, ExecutionJob } from '@rasai/prototype-contracts';
import { AppShell, Button, Callout, ContextPill, Drawer, MetricCard, PageHeader, Panel, ProgressBar, ProgressSteps, SimpleTable, StatusBadge, TabsView, TrendChart } from '@rasai/prototype-ui';

const nav = [
 {label:'Dashboard',href:'/',icon:<LayoutDashboard size={17}/>},
 {label:'Auditorias',href:'/audits',icon:<ScanSearch size={17}/>},
 {label:'Execuções',href:'/executions',icon:<Activity size={17}/>,badge:'3'},
 {label:'Agendamentos',href:'/schedules',icon:<CalendarClock size={17}/>},
 {label:'Relatórios',href:'/reports',icon:<FileChartColumn size={17}/>},
 {label:'Search Intelligence',href:'/search',icon:<SearchCheck size={17}/>},
 {label:'Integrações',href:'/integrations',icon:<PlugZap size={17}/>},
 {label:'Configurações',href:'/settings',icon:<Settings2 size={17}/>},
];

function UserChip(){ return <div className="user-chip"><div className="avatar">AM</div><div><strong>Ana Martins</strong><span>Analyst · ACME Digital</span></div></div>; }
function Context(){ return <><ContextPill label="Organização" value="ACME Digital"/><ContextPill label="Workspace" value="Digital Experience"/><ContextPill label="Projeto" value="Portal"/><ContextPill label="Property" value="portal.example"/><ContextPill label="Ambiente" value="Produção"/></>; }

function Dashboard(){
 const {data} = useQuery({queryKey:['dashboard'],queryFn:()=>mockSaas.clientDashboard(),refetchInterval:3000});
 if(!data) return <Panel><div className="empty">Carregando visão operacional...</div></Panel>;
 const running = data.jobs.find(j=>j.status==='RUNNING');
 return <><PageHeader eyebrow="Operação" title="Visão geral" description="Saúde da propriedade, processamento atual e sinais que exigem atenção." actions={<><Button variant="secondary">Comparar períodos</Button><AuditWizardTrigger/></>}/>
 <div className="grid metrics">{data.metrics.map(m=><MetricCard key={m.label} {...m}/>)}</div>
 <div className="grid two">
  <Panel title="Evolução de readiness" subtitle="Últimas execuções comparáveis"><TrendChart values={[68,71,74,79,81]} labels={['05/09','07/09','09/09','11/09','Hoje']} name="SARI"/></Panel>
  <Panel title="Em processamento" subtitle="Atualização simulada a cada 3 segundos">{running?.progress ? <div><div className="execution-title"><div><h3>{running.title}</h3><p className="mono">{running.auditId} · {running.jobId}</p></div><StatusBadge status={running.status}/></div><div className="progress-big">{running.progress.percent}%</div><ProgressBar value={running.progress.percent}/><p className="subtle">{running.progress.message}</p><ProgressSteps stages={running.progress.stages}/></div>:<p>Sem processamento atual.</p>}</Panel>
 </div>
 <div className="grid two" style={{marginTop:16}}>
  <Panel title="Próximos agendamentos" subtitle="Schedules ainda não materializados em jobs"><div className="list">{data.schedules.filter(x=>x.status==='ACTIVE').map(s=><div className="list-item" key={s.scheduleId}><div className="row"><div><strong>{s.name}</strong><p>{s.recurrenceLabel} · {s.timezone}</p></div><StatusBadge status="SCHEDULED" label={s.overlapPolicy}/></div></div>)}</div></Panel>
  <Panel title="Auditorias recentes"><SimpleTable columns={[{key:'auditId',label:'Audit'},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>},{key:'sari',label:'SARI'},{key:'geo',label:'GEO'}]} rows={data.audits.slice(0,4)}/></Panel>
 </div></>;
}

function AuditWizardTrigger(){ return <Drawer title="Nova auditoria" description="Configuração orientada por objetivo; o backend definitivo receberá apenas o contrato canônico." trigger={<Button><Plus size={14}/> Nova auditoria</Button>}><AuditWizard/></Drawer>; }
function AuditWizard(){
 const [step,setStep]=useState(0); const [selected,setSelected]=useState(['SEO técnico','GEO','Lighthouse','CrUX','IA — recomendações']);
 const steps=['Alvo','Escopo','Análises','IA','Performance','Revisão'];
 const options=['SEO técnico','GEO','Lighthouse','CrUX','Apdex','Search Intelligence','IA — recomendações','Conteúdo'];
 const toggle=(o:string)=>setSelected(v=>v.includes(o)?v.filter(x=>x!==o):[...v,o]);
 return <div><div className="wizard-steps">{steps.map((s,i)=><div className={`wizard-step ${i===step?'active':''}`} key={s}>{i+1}. {s}</div>)}</div>
 {step===0 && <div className="stack"><div className="field"><label>URL / domínio</label><input defaultValue="https://portal.example/"/></div><div className="field"><label>Origem</label><select><option>URL / domínio</option><option>Sitemap</option><option>Lista de URLs</option></select></div></div>}
 {step===1 && <div className="stack"><Callout title="Escopo previsto">120 URLs detectadas no protótipo; a execução real fará o preflight no SaaS.</Callout><div className="field"><label>Máximo de páginas</label><input type="number" defaultValue="120"/></div><div className="field"><label>Dispositivos</label><select defaultValue="both"><option value="mobile">Mobile</option><option value="desktop">Desktop</option><option value="both">Mobile + Desktop</option></select></div></div>}
 {step===2 && <div className="option-grid">{options.map(o=><div className={`option-card ${selected.includes(o)?'active':''}`} onClick={()=>toggle(o)} key={o}><strong>{selected.includes(o)?'✓ ':''}{o}</strong><span>{selected.includes(o)?'Incluído na execução':'Clique para incluir'}</span></div>)}</div>}
 {step===3 && <div className="stack"><div className="field"><label>Provider</label><select><option>AUTO — menor custo elegível</option><option>OpenAI</option><option>Gemini</option></select></div><Callout title="Credencial efetiva">OpenAI possui credencial própria do usuário. Gemini utilizará a credencial compartilhada do RASAi.</Callout></div>}
 {step===4 && <div className="stack"><div className="field"><label>Web Performance</label><select><option>Ativo</option><option>Desativado</option></select></div><div className="field"><label>Field source</label><select><option>Automático</option><option>CrUX</option><option>PageSpeed</option></select></div></div>}
 {step===5 && <div className="stack"><Callout title="Readiness">Configuração pronta. 120 URLs, 2 dispositivos, IA Auto, Web Performance ativo.</Callout><div className="grid two"><MetricCard label="Chamadas externas" value="~840" tone="info"/><MetricCard label="Custo estimado SaaS" value="US$ 2,10" tone="warning"/></div><Panel title="Destino"><div className="split"><span className="subtle">Executar agora ou transformar a mesma configuração em schedule.</span><StatusBadge status="READY"/></div></Panel></div>}
 <div className="split" style={{marginTop:22}}><Button variant="secondary" onClick={()=>setStep(Math.max(0,step-1))}>Voltar</Button><Button onClick={()=>setStep(Math.min(5,step+1))}>{step===5?'Simular execução':'Continuar'}</Button></div></div>;
}

function Audits(){ const {data=[]}=useQuery({queryKey:['audits'],queryFn:()=>mockSaas.audits()}); return <><PageHeader eyebrow="Auditoria" title="Auditorias" description="Histórico, integridade da coleta e acesso ao resultado de cada AUD." actions={<AuditWizardTrigger/>}/><Panel title="Histórico"><SimpleTable columns={[{key:'auditId',label:'Audit'},{key:'propertyName',label:'Property'},{key:'eventTime',label:'Executada',render:r=>new Date(r.eventTime).toLocaleString('pt-BR')},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>},{key:'urlCount',label:'URLs'},{key:'sari',label:'SARI'},{key:'geo',label:'GEO'},{key:'reports',label:'Reports'}]} rows={data}/></Panel></>; }

function Executions(){ const {data=[]}=useQuery({queryKey:['jobs'],queryFn:()=>mockSaas.executionJobs(),refetchInterval:2500}); const running=data.filter(x=>x.status==='RUNNING'); const queued=data.filter(x=>x.status==='QUEUED'); const recent=data.filter(x=>!['RUNNING','QUEUED'].includes(x.status)); return <><PageHeader eyebrow="Operação" title="Central de execuções" description="Separação entre ocorrências futuras, fila materializada, processamento atual e histórico." actions={<Button><Play size={14}/> Executar agora</Button>}/><div className="grid metrics"><MetricCard label="Executando" value={String(running.length)} tone="info"/><MetricCard label="Na fila" value={String(queued.length)} tone="warning"/><MetricCard label="Concluídos hoje" value="14" tone="positive"/><MetricCard label="Com atenção" value="2" tone="danger"/></div>{running.map(j=><ExecutionCard job={j} key={j.jobId}/>)}<div className="grid two" style={{marginTop:16}}><Panel title="Fila real" subtitle="Jobs já materializados aguardando capacidade"><SimpleTable columns={[{key:'title',label:'Job'},{key:'jobType',label:'Tipo'},{key:'origin',label:'Origem'},{key:'priority',label:'Prioridade'},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>}]} rows={queued}/></Panel><Panel title="Finalizados recentemente"><SimpleTable columns={[{key:'title',label:'Execução'},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>},{key:'auditId',label:'Audit'}]} rows={recent}/></Panel></div></>; }
function ExecutionCard({job}:{job:ExecutionJob}){ return <Panel title="Executando agora" subtitle="Telemetria de progresso projetada para futura API/SSE"><div className="execution-hero"><div><div className="execution-title"><div><h3>{job.title}</h3><p className="mono">{job.jobId} · {job.auditId}</p></div><StatusBadge status={job.status}/></div><div className="progress-big">{job.progress?.percent ?? 0}%</div><ProgressBar value={job.progress?.percent ?? 0}/><p className="subtle">{job.progress?.message}</p><div className="audit-score"><div className="score-chip"><span>URLs</span><strong>120</strong></div><div className="score-chip"><span>IA calls</span><strong>9</strong></div><div className="score-chip"><span>Custo atual</span><strong>US$ 0,41</strong></div></div></div><ProgressSteps stages={job.progress?.stages ?? []}/></div></Panel>; }

function Schedules(){ const {data=[]}=useQuery({queryKey:['schedules'],queryFn:()=>mockSaas.schedules()}); return <><PageHeader eyebrow="Automação" title="Agendamentos" description="O usuário configura recorrência sem editar cron. O SaaS materializa ocorrências e jobs." actions={<Button><Plus size={14}/> Novo agendamento</Button>}/><div className="grid metrics"><MetricCard label="Ativos" value="2" tone="positive"/><MetricCard label="Pausados" value="1" tone="warning"/><MetricCard label="Próximas 24h" value="5" tone="info"/><MetricCard label="Sobreposições" value="0" tone="positive"/></div><Panel title="Schedules"><SimpleTable columns={[{key:'name',label:'Nome'},{key:'jobType',label:'Tipo'},{key:'recurrenceLabel',label:'Recorrência'},{key:'timezone',label:'Timezone'},{key:'overlapPolicy',label:'Overlap'},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>},{key:'nextRunAt',label:'Próxima',render:r=>r.nextRunAt?new Date(r.nextRunAt).toLocaleString('pt-BR'):'—'}]} rows={data}/></Panel></>; }

function Reports(){ const {data=[]}=useQuery({queryKey:['reports'],queryFn:()=>mockSaas.reports()}); return <><PageHeader eyebrow="Resultados" title="Relatórios & comparações" description="A experiência Web usa dados estruturados; os HTMLs formais continuam disponíveis como superfície de saída."/><div className="grid two"><Panel title="Evolução do SARI"><TrendChart values={[68,71,74,79,81]} labels={['05/09','07/09','09/09','11/09','13/09']}/></Panel><Panel title="Resumo do período"><div className="kpi-line"><span>Problemas resolvidos</span><strong>34</strong></div><div className="kpi-line"><span>Novos problemas</span><strong>7</strong></div><div className="kpi-line"><span>Persistentes</span><strong>18</strong></div><div className="kpi-line"><span>Melhor indicador</span><strong>GEO +9</strong></div></Panel></div><div className="report-grid" style={{marginTop:16}}>{data.map(r=><div className="report-card" key={r.reportId}><div className="split"><StatusBadge status={r.status}/><span className="source-tag">{r.source}</span></div><h3 style={{marginTop:12}}>{r.name}</h3><p>{r.auditId} · {new Date(r.generatedAt).toLocaleString('pt-BR')}</p><Button variant="secondary">Abrir relatório</Button></div>)}</div></>; }

function SearchIntelligence(){ return <><PageHeader eyebrow="Search" title="Search Intelligence" description="Visão integrada de queries, SERP, concorrentes, histórico e oportunidades."/><div className="grid metrics"><MetricCard label="Queries monitoradas" value="42" tone="info"/><MetricCard label="Top 10" value="18" trend="+3" tone="positive"/><MetricCard label="Oportunidades" value="12" tone="warning"/><MetricCard label="Concorrentes ativos" value="6"/></div><div className="grid two"><Panel title="Posição média"><TrendChart values={[18,17,15,14,12,11]} labels={['Ago 1','Ago 8','Ago 15','Ago 22','Set 1','Hoje']} name="Posição"/></Panel><Panel title="Movimentos recentes"><div className="list"><div className="list-item"><strong>“auditoria geo enterprise”</strong><p>11 → 7 · portal.example/geo</p></div><div className="list-item"><strong>“search readiness”</strong><p>23 → 14 · nova oportunidade</p></div><div className="list-item"><strong>“apdex web”</strong><p>8 → 9 · leve regressão</p></div></div></Panel></div></>; }

function Integrations(){ const {data=[]}=useQuery({queryKey:['credentials'],queryFn:()=>mockSaas.credentials()}); return <><PageHeader eyebrow="Integrações" title="Credenciais & providers" description="Credenciais compartilhadas são usadas pelo backend sem expor segredo. O usuário pode sobrepor providers individualmente com BYOK." actions={<Button><KeyRound size={14}/> Adicionar credencial própria</Button>}/><Callout title="Resolução automática">Uma credencial privada ativa prevalece para o respectivo provider. Não há fallback silencioso para credencial paga pelo SaaS quando a BYOK falha.</Callout><div className="grid three" style={{marginTop:16}}>{data.map(c=><div className="credential-card" key={c.credentialId}><header><div><h3>{c.provider}</h3><p>{c.label}</p></div><StatusBadge status={c.status}/></header><div className="kpi-line"><span>Origem</span><strong>{c.source}</strong></div><div className="kpi-line"><span>Owner</span><strong>{c.ownerLabel}</strong></div><div className="kpi-line"><span>Último uso</span><strong>{c.lastUsedAt?new Date(c.lastUsedAt).toLocaleString('pt-BR'):'—'}</strong></div><Button variant="secondary">Gerenciar</Button></div>)}</div></>; }

function Settings(){ const {data=[]}=useQuery({queryKey:['config'],queryFn:()=>mockSaas.effectiveConfig()}); return <><PageHeader eyebrow="Configuração" title="Configuração efetiva" description="Valores do console são apresentados como configurações de produto, com origem, herança e override — não como editor cru de environment variables." actions={<Button variant="secondary"><SlidersHorizontal size={14}/> Defaults do projeto</Button>}/><Callout title="Fonte de verdade">A Web não duplica validações do core. A futura API fornecerá definição, defaults, allowed values, escopos, dependências e proveniência.</Callout><Panel title="Valores resolvidos" subtitle="System → Organization → Project → Property → Environment → Template → Job" className="stack"><div>{data.map(c=><div className="config-row" key={c.key}><div><strong>{c.label}</strong><span className="mono" style={{display:'block'}}>{c.key}</span></div><strong>{String(c.value)}</strong><span>{c.scopeLabel}<br/>{c.origin}</span><StatusBadge status={c.overridden?'ATTENTION':'ACTIVE'} label={c.overridden?'Override':'Herdado'}/></div>)}</div></Panel></>; }

export default function App(){ const location=useLocation(); return <AppShell brand="RASAi" subtitle="Search & AI Readiness" nav={nav} activePath={location.pathname} topRight={<UserChip/>} context={<Context/>}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/audits" element={<Audits/>}/><Route path="/executions" element={<Executions/>}/><Route path="/schedules" element={<Schedules/>}/><Route path="/reports" element={<Reports/>}/><Route path="/search" element={<SearchIntelligence/>}/><Route path="/integrations" element={<Integrations/>}/><Route path="/settings" element={<Settings/>}/></Routes></AppShell>; }
