"""Human-facing labels for internal RASAi values used by report-catalog."""
from __future__ import annotations
import re
from typing import Any

from rasai.public_language import safe_visible_fallback, supplemental_public_label

PUBLIC_VALUE_LABELS: dict[str, str] = {
    # Ciclo de vida da auditoria e estados operacionais públicos.
    "CREATED": "Criado",
    "INITIALIZING": "Inicializando",
    "DISCOVERING": "Descobrindo URLs",
    "ACQUIRING": "Coletando páginas",
    "ANALYZING": "Analisando",
    "COMPARING": "Comparando",
    "SCORING": "Calculando pontuação",
    "RECOMMENDING": "Gerando recomendações",
    "REPORTING": "Gerando relatórios",
    "COMPLETED": "Concluído",
    "FAILED": "Falhou",
    "CANCELLED": "Cancelado",
    "FULL": "Execução completa",
    "DEGRADED": "Execução com limitações",
    "NO_AI": "Execução sem IA",
    "PROCESSING": "Em processamento",
    "RUNNING": "Em execução",
    "PENDING": "Pendente",
    "WAITING_FOR_DATA": "Aguardando pré-requisitos",
    "READY": "Disponível",
    "AVAILABLE": "Disponível",
    "GENERATED": "Gerado",
    "MEASURED": "Medido",
    "NO_SAFE_SUGGESTIONS": "Nenhuma sugestão segura",
    "NO_ELIGIBLE_FINDINGS": "Nenhum finding elegível",
    "CHAIN_EXHAUSTED": "Cadeia de provedores esgotada",
    "PROVIDER_UNAVAILABLE": "Provedor indisponível",
    # Ação, escopo, comparação e Search Intelligence.
    "REQUIRED_FIX": "Correção necessária",
    "REVIEW_RECOMMENDED": "Revisão recomendada",
    "OPTIONAL_IMPROVEMENT": "Melhoria opcional",
    "NO_ACTION": "Nenhuma ação necessária",
    "INSUFFICIENT_EVIDENCE": "Evidência insuficiente",
    "ORIGIN": "Domínio / origem",
    "DEVICE_SNAPSHOT": "Dispositivo / captura",
    "PROFILE_MEASUREMENT": "Medição por perfil",
    "SAME": "Sem diferença material",
    "DIFFERENT": "Diferente",
    "KNOWLEDGE_REFERENCE": "Referência de conhecimento",
    "SOCIAL_PLATFORM": "Plataforma social",
    "VIDEO_PLATFORM": "Plataforma de vídeo",
    "MARKETPLACE": "Marketplace",
    "NON_ORGANIC": "Resultado não orgânico",
    "NOT_ELIGIBLE": "Não elegível",
    "QUERY_INTENT": "Intenção da consulta",
    "TOPIC_COVERAGE": "Cobertura temática",
    "ENTITY_COVERAGE": "Cobertura de entidades",
    "INFORMATION_ARCHITECTURE": "Arquitetura da informação",
    "SEO_AEO_GEO": "SEO / AEO / GEO",
    "INFORMATIONAL": "Informacional",
    "TRANSACTIONAL": "Transacional",
    "REVIEW_COMPARISON": "Avaliação / comparação",
    "NEWS_EDITORIAL": "Notícias / editorial",
    "SUPPORT_DOCUMENTATION": "Suporte / documentação",
    "FORUM_UGC": "Fórum / conteúdo gerado por usuários",
    "PROFESSIONAL": "Profissional",
    "BENEFICIAL": "Benéfica",
    "USER_GENERATED": "Conteúdo gerado por usuários",
    "PRESENT": "Presente",
    "COHERENT": "Coerente",
    "INCOHERENT": "Incoerente",
    "CONSISTENT": "Consistente",
    "INCONSISTENT": "Inconsistente",
    "ALIGNED": "Alinhado",
    "MISALIGNED": "Desalinhado",
    "SATISFIED": "Satisfatória",
    "TOLERATING": "Tolerável",
    "FRUSTRATED": "Frustrada",
    "GOOD": "Bom",
    "POOR": "Ruim",
    "NEEDS_IMPROVEMENT": "Precisa melhorar",
    "STANDARD": "Padrão",
    "NONE": "Nenhuma",
    "HEALTH_SAFETY": "Saúde e segurança",
    "CIVIC_SOCIETAL": "Cívico / social",
    "OTHER_SIGNIFICANT_WELFARE": "Outro impacto significativo no bem-estar",
    "OTHER": "Outro",
    "REQUIRED": "Obrigatória",
    "THIRD_PARTY": "Terceiros",
    "VERY_HIGH": "Muito alta",
    "VERY_LOW": "Muito baixa",
    "MINIMAL": "Mínimo",
    "P0": "Crítica (P0)",
    "P1": "Muito alta (P1)",
    "P2": "Alta (P2)",
    "P3": "Média (P3)",
    "P4": "Baixa (P4)",
    "GLOBAL": "Global",
    "PAGE": "Página",
    "SNAPSHOT": "Captura",
    "NAVIGATION_TIMEOUT": "Tempo limite de navegação excedido",
    "RENDERER_ERROR": "Erro de renderização",
    "EEAT": "E-E-A-T",
    "SUCCESS": "Concluído",
    "PASS": "Aprovado",
    "FAIL": "Não aprovado",
    "WARNING": "Atenção",
    "NOT_APPLICABLE": "Não aplicável",
    "COMPLETE": "Concluído",
    "FINAL": "Concluído",
    "INFO": "Informativo",
    "PARTIAL": "Parcial",
    "FAILED_RETRYABLE": "Falha reprocessável",
    "FAILED_TERMINAL": "Falha terminal",
    "FAILED_PERMANENT": "Falha permanente",
    "FAILED_FATAL": "Falha fatal",
    "FAILURE": "Falha",
    "ERROR": "Erro",
    "DISABLED": "Desabilitado",
    "REQUESTED_NOT_EXECUTED": "Solicitado, não executado",
    "SKIPPED": "Ignorado",
    "ABSENT": "Não encontrado",
    "NO_DATA": "Sem dados",
    "INCOMPLETE": "Incompleto",
    "PRELIMINARY": "Preliminar",
    "VALID": "Válido",
    "EXPIRED": "Expirado",
    "COMPLETE_WITH_LIMITATIONS": "Concluído com limitações",
    "COMPLETED_WITH_LIMITATIONS": "Concluído com limitações",
    "APPLICATION_ERROR": "Erro da aplicação",
    "INVALID_SAMPLE": "Amostra inválida",
    "BROWSER_UNAVAILABLE": "Navegador indisponível",
    "NAVIGATION_ERROR": "Erro de navegação",
    "UNAVAILABLE": "Indisponível",
    "NOT_CONFIGURED": "Não configurado",
    "ACTIVE": "Ativo",
    "STANDBY": "Em espera",
    "TECHNICAL_ERROR": "Erro técnico",
    "CONTRACT_ERROR": "Erro no contrato de evidências",
    "QUARANTINED_FOR_AUDIT": "Indisponível nesta auditoria",
    # Domínios canônicos que podem aparecer em superfícies públicas.
    "DOMAIN": "Domínio",
    "URL": "URL",
    "URL_SET": "Conjunto de URLs",
    "SEED": "URL inicial",
    "SITEMAP": "Sitemap",
    "INTERNAL_LINK": "Link interno",
    "REDIRECT": "Redirecionamento",
    "MANUAL": "Informado manualmente",
    "HTTP_RESPONSE": "Resposta HTTP",
    "HTTP_HEADER": "Cabeçalho HTTP",
    "ROBOTS_RULE": "Regra de robots.txt",
    "SITEMAP_ENTRY": "Entrada de sitemap",
    "HTML_ELEMENT": "Elemento HTML",
    "DOM_ELEMENT": "Elemento do DOM",
    "VISUAL_SNAPSHOT": "Captura visual",
    "META_TAG": "Meta tag",
    "CANONICAL": "Canonical",
    "HEADING": "Título hierárquico (heading)",
    "LINK": "Link",
    "STRUCTURED_DATA": "Dados estruturados",
    "MAIN_CONTENT": "Conteúdo principal",
    "TEXT_EXCERPT": "Trecho de texto",
    "AI_ANALYSIS": "Análise por IA",
    "COMPARISON": "Comparação",
    "ORGANIZATION": "Organização",
    "PERSON": "Pessoa",
    "PRODUCT": "Produto",
    "SERVICE": "Serviço",
    "PLACE": "Local",
    "BRAND": "Marca",
    "TOPIC": "Tópico",
    "OTHER": "Outro",
    "OBSERVED_API": "API observada",
    "OBSERVED_SYNTHETIC": "Observação sintética",
    "IMPORTED": "Importado",
    "FIXTURE": "Dados de teste (fixture)",
    "MODELED": "Modelado",
    "AI_INFERRED": "Inferido por IA",
    "SEARCH_CONSOLE": "Google Search Console",
    "PROPERTIES": "Propriedades",
    "SITEMAPS": "Sitemaps",
    "SEARCH_ANALYTICS": "Desempenho de pesquisa",
    "SEARCH_APPEARANCE": "Aparência na pesquisa",
    "URL_INSPECTION": "Inspeção de URL",
    "GENERATIVE_AI_PERFORMANCE_EXPORT": "Exportação de desempenho em IA generativa",
    "GENERATIVE_AI_CONTROL": "Controle de IA generativa",
    "BING_WEBMASTER": "Bing Webmaster Tools",
    "PAGE_CONTENT": "Conteúdo da página",
    "AI_HYPOTHESIS": "Hipótese por IA",
    "SERP_RELATED": "Relacionada à SERP",
    "COMPETITOR_DISCOVERY": "Descoberta de concorrentes",
    "EXTERNAL": "Externo",
    "APDEX_NAVIGATION": "Apdex de navegação",
    "APDEX_EXPERIENCE": "Apdex de experiência",
    "EXPERIENCE": "Experiência",
    "SEO": "SEO",
    "GEO_SEARCH_AI": "GEO / Busca e IA",
    "BEST_PRACTICES": "Boas práticas",
    "SEMANTICS": "Semântica",
    "YMYL": "YMYL",
    "SECURITY": "Segurança",
    "VULNERABILITIES": "Vulnerabilidades",
    "HTML_CSS": "HTML / CSS",
    "CRAWLABILITY": "Rastreabilidade por crawlers",
    "COMPETITIVE_INTELLIGENCE": "Inteligência competitiva",
    "TECHNICAL_QUALITY": "Qualidade técnica",
    "DESKTOP": "Desktop",
    "MOBILE": "Dispositivo móvel",
    "BOTH": "Ambos",
    "STATIC_OR_SSR": "Estática ou renderizada no servidor (SSR)",
    "HYDRATED": "Renderizada no servidor com hidratação",
    "CSR_SPA": "SPA renderizada no cliente (CSR)",
    "PLAYWRIGHT_CHROMIUM": "Chromium via Playwright",
    "CRITICAL": "Crítica",
    "GOOGLE_SEARCH_CONSOLE": "Google Search Console",
    "MICROSOFT_CLARITY": "Microsoft Clarity",
    "COMMON_CRAWL": "Common Crawl",
    "SEARCH_INTELLIGENCE": "Inteligência de busca / SERP",
    "SERP": "SERP",
    "PAGESPEED_INSIGHTS": "PageSpeed Insights",
    "CRUX_API": "CrUX API",
    "MDN_OBSERVATORY": "MDN HTTP Observatory",
    "OSV": "OSV",
    "CISA_KEV": "CISA KEV",
    "DIRECT_PUBLIC_INDEX_API": "API pública de índice",
    "DIRECT_OFFICIAL_API": "API oficial da fonte",
    "NORMALIZED_EXPORT": "Exportação normalizada",
    "MANUAL_TRANSCRIPTION": "Transcrição manual",
    "CONTROLLED_PROTOCOL": "Protocolo controlado",
    "EXTERNAL_AUTOMATION": "Automação externa",
    "LIVE_RECOLLECTION": "Coleta ao vivo desta auditoria",
    "REUSED_EVIDENCE": "Evidência reutilizada",
    "REPLAY_SAFE": "Reutilizável sem nova coleta",
    "NON_LIVE_SOURCE": "Fonte sem coleta ao vivo",
    "OBSERVED_EXTERNAL_DATA": "Dados externos observados",
    "HISTORICAL_WEB_ARCHIVE": "Arquivo histórico da web",
    "MIXED": "Origem temporal mista",
    "LEGACY": "Origem legada",
    "DETERMINISTIC_CORRELATIONAL_001": "Correlação determinística de evidências",
    "CONTENT_COMPARISON_DISABLED": "Comparação de conteúdo desabilitada",
    "CUSTOMER_URL_REQUIRED": "URL do site auditado necessária",
    "CUSTOMER_CONTENT_UNAVAILABLE": "Conteúdo do site auditado indisponível",
    "NO_ELIGIBLE_COMPETITOR_CANDIDATES": "Nenhum candidato concorrente elegível",
    "COMPETITOR_CONTENT_UNAVAILABLE": "Conteúdo dos concorrentes indisponível",
    "PUBLIC_WEB_DESTINATION_BLOCKED": "Destino público bloqueado pela política de aquisição",
    "SERP_OBSERVATION_UNAVAILABLE": "Observação de SERP indisponível",
    "CLASSIFICATION_ONLY": "Somente classificação",
    "NOT_FOUND_WITHIN_DEPTH": "Não encontrado na profundidade coletada",
    "FOUND": "Encontrado na profundidade coletada",
    "ORGANIC_CANDIDATE": "Candidato orgânico",
    "PUBLIC_AUTHORITY": "Autoridade pública",
    "NON_SCORING": "Não participa da pontuação",
    "BOUNDED_AI_RESOURCE_ASSESSMENT": "Avaliação de IA limitada e vinculada a evidências",
    "SHARED_ACQUISITION": "Aquisição compartilhada",
    "DETERMINISTIC_BASELINE": "Baseline determinístico",
    "UNKNOWN_ACTION": "Ação não classificada",
    "RATE_LIMITED": "Limite de requisições atingido",
    "REQUEST_FAILED": "Falha na requisição",
    "NETWORK_ERROR": "Erro de rede",
    "DNS": "Erro de DNS",
    "CONNECTION": "Erro de conexão",
    "TIMEOUT": "Tempo limite excedido",
    "TLS": "Erro TLS",
    "PROTOCOL": "Erro de protocolo",
    "REDIRECT_LOOP": "Loop de redirecionamento",
    "TOO_MANY_REDIRECTS": "Redirecionamentos em excesso",
    "INVALID_REDIRECT": "Redirecionamento inválido",
    "CONSOLE_ERROR": "Erro de console",
    "CORS": "Restrição CORS",
    "HTTP_ERROR": "Erro HTTP",
    "AUTH_ERROR": "Erro de autenticação",
    "QUOTA_ERROR": "Cota excedida",
    "CREDIT_ERROR": "Crédito indisponível",
    "RATE_LIMIT_ERROR": "Limite de requisições atingido",
    "MODEL_ERROR": "Erro do modelo",
    "PERMISSION_ERROR": "Erro de permissão",
    "TIMEOUT_ERROR": "Tempo limite excedido",
    "SERVER_ERROR": "Erro do servidor",
    "BUSINESS_ERROR": "Erro de regra de negócio",
    "EMPTY_RESPONSE": "Resposta vazia",
    "INVALID_RESPONSE": "Resposta inválida",
    "TOOL_CALL": "Resposta do provedor solicitou uso de ferramenta não permitido",
    "UNKNOWN_PROVIDER_ERROR": "Erro não identificado do provedor",
    "QUARANTINED": "Em quarentena",
    "QUARANTINED_FOR_AUDIT": "Indisponível nesta auditoria",
    "MAX_PAGES_REACHED": "Limite máximo de páginas atingido",
    "RENDERED_LINKS_OUTSIDE_AUDIT_UNIVERSE_MAX_PAGES": "Links renderizados fora do universo auditado devido ao limite máximo de páginas",
    "RENDERED_DISCOVERY_GAP": "Lacuna na descoberta renderizada",
    "RENDER_DISCOVERY_GAP": "Lacuna na descoberta renderizada",
    "DISCOVERY_GAP": "Lacuna de descoberta",
    "PARTIAL_RENDERED_DISCOVERY": "Descoberta renderizada parcial",
    "AI_PROVIDER_UNAVAILABLE": "Provedor de IA indisponível",
    "AI_NOT_AUTHORIZED_FOR_EXECUTION": "IA não autorizada para execução nesta auditoria",
    "AI_PREREQUISITES_INCOMPLETE": "Pré-requisitos da IA ainda não concluídos",
    "AI_PROVIDER_NOT_CONFIGURED": "Provedor de IA não configurado",
    "EXECUTION_POLICY": "Política de execução",
    "PREREQUISITE": "Pré-requisito",
    "ORCHESTRATION": "Orquestração",
    "EXTERNAL_SERVICE": "Serviço externo",
    "CONFIGURATION": "Configuração",
    "CONFIGURATION_REQUIRED": "Configuração necessária",
    "SERVICE_INCOMPLETE": "Serviço incompleto",
    "TECHNICAL_AI": "IA técnica",
    "TECHNICAL_AI_CONTRACT_VALIDATION_ERROR": "Erro de validação do contrato da IA técnica",
    "TECHNICAL_AI_UNAVAILABLE": "IA técnica indisponível",
    "AI_CONTRACT": "Contrato de IA",
    "AI_PROVIDER": "Provedor de IA",
    "IMPROVEMENT_CONFIGURATION_INVALID": "Configuração da análise profunda inválida",
    "IMPROVEMENT_INCOMPLETE": "Análise profunda incompleta",
    "REPROCESS_ELIGIBLE": "Elegível para reprocessamento",
    "SITE_URL_REQUIRED": "URL do site necessária",
    "SYNTHETIC_APDEX": "Apdex sintético",
    "EXPERIENCE_APDEX": "Apdex de experiência",
    "AUDIT": "Auditoria",
    "TARGET_SITE": "Site / propriedade auditada",
    "AUDITOR_INTERNAL": "Auditor RASAi",
    "EXTERNAL_PROVIDER": "Fornecedor / dependência externa",
    "ENVIRONMENTAL": "Ambiente / infraestrutura",
    "AI_REQUIREMENTS": "Requisitos da IA",
    "AI_RESULT_STALE": "Resultado de IA desatualizado",
    "AUDIT_INCOMPLETE_RECOVERABLE": "Auditoria incompleta, passível de retomada",
    "AUDIT_RESUME_PLAN_UNAVAILABLE": "Plano seguro de retomada indisponível",
    "CATALOG_ADDED_AFTER_INITIAL_COMPLETION": "Catálogo adicionado após a conclusão inicial",
    "CATALOG_EXTENSION": "Extensão de catálogo",
    "COMPETITIVE_AI_OUTPUT_INVALID": "Saída inválida da IA competitiva",
    "CONSOLIDATED_LONGITUDINAL_OUTPUT_INVALID": "Saída longitudinal consolidada inválida",
    "CONTENT_HTTP_STATUS": "Status HTTP do conteúdo",
    "CONTENT_REMEDIATION_EXECUTION_FAILURE": "Falha na execução da remediação de conteúdo",
    "CONTENT_UNSUPPORTED_MEDIA_TYPE": "Tipo de mídia do conteúdo não suportado",
    "CORE_RECOVERY": "Retomada do núcleo da auditoria",
    "CORE_RECOVERY_EXCEPTION": "Erro na retomada do núcleo da auditoria",
    "DIRECTED_ANALYSIS_OUTPUT_INVALID": "Saída inválida da Análise Direcionada",
    "EVIDENCE_COVERAGE": "Cobertura de evidências",
    "EVIDENCE_DEPENDENCY": "Dependência de evidências",
    "EVIDENCE_VERSION": "Versão da evidência",
    "EXECUTION_INTERRUPTED": "Execução interrompida",
    "IMPROVEMENT_CALL_WRAPPER_ERROR": "Erro na chamada da análise profunda",
    "IMPROVEMENT_OUTPUT_INVALID": "Saída inválida da análise profunda",
    "IMPROVEMENT_WALL_CLOCK_TIMEOUT": "Tempo total da análise profunda excedido",
    "INTERNAL": "Interno",
    "INVALID_JSON": "JSON inválido",
    "INVALID_JSON_OBJECT": "Objeto JSON inválido",
    "M20_UNEXPECTED_CONTRACT_ERROR": "Erro inesperado no contrato da análise",
    "M2_DISCOVERY_ACQUISITION_FAILED": "Falha na aquisição durante a descoberta",
    "NETWORK": "Rede",
    "PASSIVE_SECURITY": "Segurança passiva",
    "PASSIVE_SECURITY_EXTERNAL_COVERAGE_INCOMPLETE": "Cobertura externa de segurança passiva incompleta",
    "PASSIVE_SECURITY_INPUT_CHANGED": "Entradas da segurança passiva alteradas",
    "PERSISTED_RENDER_ARTIFACT_MISSING": "Artefato de renderização persistido ausente",
    "PERSISTED_EXTRACTION_SOURCE_MISSING": "Fonte de extração persistida ausente",
    "PERSISTED_EVIDENCE_MISSING": "Evidência persistida ausente",
    "PLANNED_WORK_NOT_EXECUTED": "Etapa planejada não executada",
    "RATE_LIMIT": "Limite de requisições",
    "RECOVERY": "Retomada",
    "RECOVERY_CONTRACT": "Contrato de retomada",
    "REFUSAL": "Recusa do provedor",
    "REPROCESS_PREREQUISITES_INCOMPLETE": "Pré-requisitos do reprocessamento ainda não concluídos",
    "REQUEST_REMEDIATION_OUTPUT_INVALID": "Saída inválida da remediação de requisições",
    "SEARCH_INTELLIGENCE_INCOMPLETE": "Inteligência de busca incompleta",
    "SEARCH_INTELLIGENCE_RUNTIME_ERROR": "Erro na execução da Inteligência de busca",
    "SEARCH_PROVIDER": "Provedor de busca",
    "SEARCH_SKIPPED_SOURCE_BLOCKER": "Fonte de busca ignorada por bloqueio técnico",
    "SEMANTIC_CONTEXT_NOT_EXECUTED": "Contexto semântico não executado",
    "SEMANTIC_CONTEXT_NOT_RECOVERABLE": "Contexto semântico não recuperável",
    "SERP_CONSOLE_RUNTIME_ERROR": "Erro na execução da coleta SERP",
    "SERP_DISABLED": "SERP desabilitada",
    "SERP_REQUESTED_DEPTH_INCOMPLETE": "Profundidade solicitada da SERP não concluída",
    "SERVICE_DISABLED": "Serviço desabilitado",
    "SERVICE_UNAVAILABLE": "Serviço indisponível",
    "SOURCE_BLOCKED": "Fonte bloqueada",
    "TECHNICAL_AI_PARTIAL_REQUIREMENTS": "Requisitos parciais da IA técnica",
    "TIMEOUTERROR": "Tempo limite excedido",
    "WALL_CLOCK_TIMEOUT": "Tempo total de execução excedido",
    "WEB_PERFORMANCE_RUN_UNAVAILABLE": "Execução de desempenho web indisponível",
    "WEB_PERFORMANCE_STATE_UNAVAILABLE": "Estado de desempenho web indisponível",
    "WORKER_RESULT_MISSING": "Resultado do executor ausente",
    "SEMANTIC_EFFECTIVE_RESULT_CHANGED": "Resultado semântico efetivo alterado",
    "ATTEMPT_ABANDONED": "Tentativa interrompida",
    "INTEGRITY": "Integridade",
    "RESULT_STALE": "Resultado desatualizado",
    "SEMANTIC_AI_NO_SUCCESSFUL_CAUSAL_ATTEMPT": "Nenhuma tentativa válida de IA semântica foi concluída para este contexto",
    "EXPLICIT": "Explícito",
    "FALLBACK": "Alternativa automática (fallback)",
    "HTTP_429": "HTTP 429 - limite de requisições",
    "HTTP_503": "HTTP 503 - serviço indisponível",
    "ACCESSIBILITY_CATEGORY_NOT_REQUESTED": "Categoria de acessibilidade não solicitada",
    "ACCESSIBILITY_SCORE_UNAVAILABLE": "Pontuação de acessibilidade indisponível",
    "BUSINESS_AUTHENTICATION_OR_PERMISSION": "Autenticação ou permissão do serviço",
    "BUSINESS_CREDIT_OR_BILLING": "Crédito ou faturamento do serviço",
    "BUSINESS_QUOTA_OR_PLAN": "Cota ou limite do plano do serviço",
    "SERP_PROVIDER_ERROR": "Erro do provedor de SERP",
    "TECHNICAL_PROVIDER_OR_RUNTIME": "Falha técnica do provedor ou da execução",
    "TECHNICAL_RATE_LIMIT": "Limite técnico de requisições atingido",
    "TECHNICAL_TIMEOUT": "Tempo limite técnico excedido",
    "TECHNICAL_TRANSIENT_PROVIDER": "Falha transitória do provedor",
    "AI_PROVIDER_CHAIN_EXHAUSTED": "Nenhum provedor de IA elegível permaneceu disponível",
    "AI_NOT_CONFIGURED": "IA selecionada sem configuração elegível",
    "AI_NOT_CONFIGURED_FOR_M24": "IA técnica não configurada",
    "AI_NOT_CONFIGURED_OR_QUARANTINED": "IA sem configuração elegível ou indisponível nesta auditoria",
    "AI_DISABLED_BY_CONFIGURATION": "IA desabilitada por configuração",
    "AI_CONTEXT_NOT_READY": "Contexto necessário para IA ainda não está pronto",
    "AI_WAITING_FOR_DATA": "IA aguardando dados necessários",
    "AI_OUTPUT_MISSING_RULE": "Resposta da IA sem a regra esperada",
    "PROVIDER_QUARANTINED": "Provedor indisponível nesta auditoria",
    "INVALID_NORMALIZED_OUTPUT": "Saída normalizada da IA inválida",
    "INVALID_PROVIDER_CONTRACT": "Contrato do provedor de IA inválido",
    "INCOMPLETE_SEMANTIC_OUTPUT": "Saída semântica incompleta",
    "CONTENT_EVIDENCE_INSUFFICIENT": "Evidência de conteúdo insuficiente",
    "MAIN_CONTENT_UNAVAILABLE": "Conteúdo principal indisponível",
    "SEMANTIC_EVIDENCE_UNAVAILABLE": "Evidência semântica indisponível",
    "SOURCE_QUALITY_BLOCKED": "Aquisição técnica bloqueada pela qualidade da origem",
    "SKIPPED_SOURCE_BLOCKER": "Ignorado por bloqueio técnico da origem",
    "ADD_CONTEXT": "Adicionar contexto",
    "EDIT_CONTENT": "Editar conteúdo",
    "ADD_OR_CORRECT": "Adicionar ou corrigir",
    "ADD_OR_RESTRUCTURE_ANSWER": "Adicionar ou reestruturar resposta",
    "CLARIFY_ENTITY_RELATIONSHIPS": "Esclarecer relações entre entidades",
    "CLOSE_INTENT_GAPS": "Fechar lacunas de intenção",
    "DISAMBIGUATE_ENTITY": "Desambiguar entidade",
    "DISCOVERY_ACCESS": "Acesso e descoberta",
    "TECHNICAL_ACCESSIBILITY": "Acessibilidade técnica",
    "INDEXABILITY": "Indexabilidade e canonicalização",
    "CONTENT_EXTRACTABILITY": "Renderização e extração",
    "SEMANTIC_STRUCTURE": "Estrutura semântica",
    "ENTITY_CLARITY": "Clareza de entidades",
    "STRUCTURED_DATA": "Dados estruturados",
    "ANSWERABILITY": "Capacidade de resposta",
    "CITATION_READINESS": "Preparação para citação",
    "EVIDENCE_TRUST": "Evidências e confiabilidade",
    "INTENT_COVERAGE": "Cobertura de intenções",
    "CONTENT_VALUE": "Valor do conteúdo",
    "OVERALL_READINESS": "Índice de Prontidão Search & IA",
    "NOT_REQUESTED": "Não solicitado",
    "OBTAINED": "Obtido",
    "OBSERVED": "Observado",
    "INVALID": "Inválido",
    "BLOCKED": "Bloqueado",
    "UNKNOWN": "Não determinado",
    "PARTIAL_RETRYABLE": "Parcial - reprocessamento disponível",
    "PARTIAL_BLOCKED": "Parcial - há bloqueios",
    "EXPIRED_FOR_COMPLETION": "Expirado para conclusão",
    "CUSTOMER": "Site auditado",
    "COMPETITOR_CANDIDATE": "Candidato concorrente",
    "CONTENT_REMEDIATION": "Remediação de conteúdo",
    "IMPROVEMENT_INTELLIGENCE": "Análise profunda e melhorias",
    "COMPETITIVE_INTELLIGENCE": "Inteligência competitiva",
    "SEMANTIC_M7": "Análise semântica",
    "REQUEST_REMEDIATION": "Remediação de requisições",
    "M24_TECHNICAL_REMEDIATION": "Remediação técnica de rastreamento e descoberta",
    "INTERPRETED": "Interpretado",
    "NOT_DETERMINABLE": "Não determinável",
    "FINANCIAL_SECURITY": "Segurança financeira",
    "GENERAL": "Público geral",
    "NOT_EXPECTED": "Experiência prévia não esperada",
    "PRODUCT_SERVICE": "Produto ou serviço",
    "FIRST_PARTY": "Conteúdo próprio",
    "LOW": "Baixa",
    "MEDIUM": "Média",
    "HIGH": "Alta",
    "AI_INFERENCE": "Inferência de IA",
    "AUTO": "Automático",
    "NOT_CONSOLIDATED": "Não consolidado",
    "CONSOLIDATED": "Consolidado",
    # Segurança passiva e tipos técnicos expostos ao usuário.
    "OBSERVATION": "Observação",
    "CONFIGURATION_WEAKNESS": "Fragilidade de configuração",
    "EXPOSURE": "Exposição",
    "POTENTIAL_VULNERABILITY": "Vulnerabilidade potencial",
    "KNOWN_VULNERABILITY": "Vulnerabilidade conhecida",
    "THREAT_REPUTATION": "Inteligência de ameaças / reputação",
    "RUNTIME_FAILURE": "Falha em tempo de execução",
    "INFORMATION_DISCLOSURE": "Exposição de informação",
    "TRANSPORT": "Transporte",
    "HTTP_SECURITY": "Segurança HTTP",
    "BROWSER_SECURITY": "Segurança do navegador",
    "COOKIES": "Cookies",
    "PRIVACY_BROWSER": "Privacidade / navegador",
    "CROSS_ORIGIN": "Políticas entre origens",
    "MIXED_CONTENT": "Conteúdo misto",
    "RESOURCE_INTEGRITY": "Integridade de recursos",
    "FORMS": "Formulários",
    "IFRAMES": "Iframes",
    "RUNTIME": "Tempo de execução",
    "VULNERABILITY_INTELLIGENCE": "Inteligência de vulnerabilidades / CVE",
    "INLINE": "Em linha",
    "FILENAME": "Nome do arquivo",
    "HEADER": "Cabeçalho HTTP",
    "MANIFEST": "Manifesto",
    "SBOM": "SBOM",
    "SCRIPT": "Script",
    "STYLESHEET": "Folha de estilos",
    "RESOURCE": "Recurso",
    "FORM": "Formulário",
    "IFRAME": "Iframe",
    "IMG": "Imagem",
    "SOURCE": "Fonte",
    "VIDEO": "Vídeo",
    "AUDIO": "Áudio",
    "TRACK": "Faixa",
    # Fontes observacionais e integrações públicas.
    "GOOGLE_SEARCH_CONSOLE_SEARCH_ANALYTICS": "Google Search Console - Análise de pesquisa",
    "GOOGLE_SEARCH_CONSOLE_SEARCH_APPEARANCE": "Google Search Console - Aparência na pesquisa",
    "GOOGLE_SEARCH_CONSOLE_URL_INSPECTION": "Google Search Console - Inspeção de URL",
    "GOOGLE_SEARCH_CONSOLE_PROPERTIES": "Google Search Console - Propriedades",
    "GOOGLE_SEARCH_CONSOLE_SITEMAPS": "Google Search Console - Sitemaps",
    "GOOGLE_SEARCH_CONSOLE_GENERATIVE_AI_PERFORMANCE_EXPORT": "Google Search Console - Desempenho de IA generativa",
    "GOOGLE_SEARCH_CONSOLE_GENERATIVE_AI_CONTROL": "Google Search Console - Controle de IA generativa",
    "CHROME_UX_REPORT_HISTORY": "Histórico do Chrome UX Report",
    "COMMON_CRAWL_CDX_HISTORY": "Common Crawl",
    "MICROSOFT_CLARITY_LIVE_INSIGHTS": "Microsoft Clarity",
}


# Códigos semânticos literais encontrados na varredura transversal da #96.
# O contrato é explícito de propósito: novos códigos continuam falhando no teste de
# enforcement até receberem um rótulo pt-BR adequado.
PUBLIC_VALUE_LABELS.update({
    "AI_DISABLED_FOR_THIS_RPR": "IA desabilitada para este reprocessamento",
    "AI_NOT_REQUESTED_FOR_AUDIT": "IA não solicitada para esta auditoria",
    "AI_PROVIDER_ATTEMPT_BUDGET_EXHAUSTED": "Limite de tentativas do provedor de IA esgotado",
    "AI_PROVIDER_NOT_RESOLVED": "Provedor de IA não definido",
    "AI_WAITING_FOR_PREREQUISITES": "IA aguardando pré-requisitos",
    "ALIGNED_WINDOW": "Janela temporal alinhada",
    "AUDIT_DELETION_CANCELLED": "Exclusão da auditoria cancelada",
    "BROWSER_WORKER_RENDER_EXCEPTION": "Falha do navegador durante a renderização",
    "BR_GEO_034_BLOCKS_TYPE_IDENTIFICATION": "A regra BR-GEO-034 impede identificar o tipo",
    "CANONICAL_ABSENT": "Canonical ausente",
    "CANONICAL_TARGET_OUTSIDE_AUDITED_UNIVERSE": "Destino canonical fora do universo auditado",
    "CDP_RESPONSE_BODY_UNAVAILABLE": "Corpo da resposta indisponível no navegador",
    "COMMON_CRAWL_PARTIAL_PROVIDER_ERRORS": "Common Crawl retornou erros parciais do provedor",
    "COMMON_CRAWL_PROVIDER_ERRORS": "Common Crawl retornou erros do provedor",
    "COMPETITIVE_CONTENT": "Conteúdo competitivo",
    "COMPETITIVE_CONTENT_PARTIAL": "Conteúdo competitivo parcial",
    "CONFIGURATION_INVALID": "Configuração inválida",
    "CONTENT_COMPARISON_REQUIRED": "Comparação de conteúdo necessária",
    "CONTENT_EXTRACTION_PREREQUISITE_BLOCKED": "Pré-requisito da extração de conteúdo bloqueado",
    "CONTENT_LOST_AFTER_RENDER": "Conteúdo perdido após a renderização",
    "CONTENT_RECOVERED_BY_BOUNDED_SCROLL": "Conteúdo recuperado por rolagem controlada",
    "CONTENT_REMEDIATION_RETRY_INCOMPLETE": "Nova tentativa de remediação de conteúdo incompleta",
    "CORE_DERIVED": "Derivações centrais da auditoria",
    "CRAWLER_ACCESS_UNRESOLVED": "Acesso do crawler não resolvido",
    "CTRL_C_INTERACTIVE_CONSOLE": "Interrupção solicitada pelo usuário no console",
    "CURRENT_DISCOVERY_GATE_BLOCKED": "Gate atual de descoberta bloqueado",
    "DECODED_DOCUMENT_EXCEEDS_CAPTURE_LIMIT": "Documento decodificado excede o limite de captura",
    "DERIVED_RECOMPUTE": "Recálculo de dados derivados",
    "ESSENTIAL_CONTENT_NOT_IDENTIFIED": "Conteúdo essencial não identificado",
    "ESSENTIAL_CONTENT_NOT_RECOVERED_BY_BOUNDED_SCROLL": "Conteúdo essencial não recuperado por rolagem controlada",
    "EXPERIENCE_SESSION_WARM_REQUIRES_ISOLATED_ACQUISITION": "Sessão aquecida de experiência exige aquisição isolada",
    "EXTERNAL_API": "API externa",
    "FINDING_NOT_REOPENABLE": "Achado não pode ser reaberto",
    "GSC_RETRY_NOT_MATERIALIZED": "Nova tentativa do Search Console não materializou resultado",
    "IMPROVEMENT_OUTPUT_PARTIAL": "Saída parcial da análise profunda",
    "IMPROVEMENT_REPAIR_INVALID": "Correção da análise profunda inválida",
    "IMPROVEMENT_REPAIR_PARTIAL": "Correção parcial da análise profunda",
    "IMPROVEMENT_RETRY_NOT_MATERIALIZED": "Nova tentativa da análise profunda não materializou resultado",
    "INJECTED_GATEWAY_REQUIRES_ISOLATED_ACQUISITION": "Gateway injetado exige aquisição isolada",
    "ISOLATED_BY_CONFIGURATION": "Aquisição isolada por configuração",
    "LIVE_PAGE_CAPTURE_HOOK_NOT_REACHED": "Captura da página ao vivo não foi alcançada",
    "LOGICALLY_DELETED": "Excluída logicamente",
    "M21_RUNTIME_FAILURE": "Falha na execução de Web Performance",
    "M23_RUNTIME_FAILURE": "Falha na execução do Apdex de navegação",
    "M5_FOUNDATION": "Fundamentos técnicos",
    "MAIN_DOCUMENT_EXCEEDS_CAPTURE_LIMIT": "Documento principal excede o limite de captura",
    "MATERIAL_DEVICE_DIFFERENCE": "Diferença material entre dispositivos",
    "METRICS_CAPTURE_FAILED": "Falha na captura de métricas",
    "NON_OVERLAPPING": "Períodos sem sobreposição",
    "NOT_FIXED": "Não corrigido",
    "NOT_VERIFIABLE": "Não verificável",
    "NO_AUDIT_CLI_CONTEXT": "Contexto da auditoria indisponível na linha de comando",
    "NO_BASELINE_ATTRIBUTION_APPLICABILITY_SIGNAL": "Sem sinal de aplicabilidade para atribuição de baseline",
    "NO_COMMON_CRAWL_CAPTURE_OBSERVED": "Nenhuma captura observada no Common Crawl",
    "NO_CONSOLIDATED_COMPETITIVE_EVIDENCE": "Sem evidência competitiva consolidada",
    "NO_CVE_FROM_OSV": "Nenhum CVE retornado pelo OSV",
    "NO_DEVICE_SNAPSHOTS": "Sem capturas por dispositivo",
    "NO_DOMAIN_SERP_OBSERVATIONS": "Sem observações SERP para o domínio",
    "NO_FRESHNESS_SIGNAL": "Sem sinal de atualidade",
    "NO_MATERIAL_BASELINE_INTENT_GAP_SET": "Sem lacuna material de intenção no baseline",
    "NO_RENDERED_CONTEXTS": "Sem contextos renderizados",
    "NO_VERSIONED_COMPONENT_IDENTIFIED": "Nenhum componente versionado identificado",
    "OBSERVED_URL_RATIO_BELOW_CORROBORATION_THRESHOLD": "Proporção de URLs observadas abaixo do limite de corroboração",
    "ONE_DEVICE_SNAPSHOT_MISSING": "Captura ausente para um dos dispositivos",
    "OPTIONAL_DEEP_TLS_NOT_ENABLED_IN_INITIAL_SCOPE": "Análise TLS aprofundada opcional não habilitada no escopo inicial",
    "PARTIALLY_FIXED": "Parcialmente corrigido",
    "PARTIAL_OVERLAP": "Sobreposição parcial",
    "PASSIVE_SECURITY_NOT_SELECTED": "Segurança passiva não selecionada",
    "PHYSICAL_CLEANUP_PENDING": "Limpeza física pendente",
    "PLAYWRIGHT_METRICS_UNAVAILABLE": "Métricas do navegador indisponíveis",
    "POTENTIAL_CANNIBALIZATION": "Possível canibalização",
    "PREPARATION_FAILED": "Falha na preparação",
    "RAW_OR_RENDERED_UNAVAILABLE": "Conteúdo bruto e renderizado indisponíveis",
    "RENDER_FAILED_BUT_RAW_FALLBACK_REMAINED_ANALYZABLE": "Renderização falhou, mas o conteúdo bruto permaneceu analisável",
    "RENDER_FAILURE_PREVENTED_CONTENT_RECOVERY": "Falha de renderização impediu recuperar o conteúdo",
    "REUSED_GOVERNED_TASK": "Tarefa governada reutilizada",
    "ROBOTS_ABSENT": "robots.txt ausente",
    "RPR_GOVERNED_RESULT_REUSED": "Resultado governado do reprocessamento reutilizado",
    "RULE_EXECUTION_NOT_REOPENABLE": "Execução da regra não pode ser reaberta",
    "SAME_SESSION_LAZY_PROBE_FAILED": "Sondagem de conteúdo tardio na mesma sessão falhou",
    "SAME_SESSION_LAZY_PROBE_TIMEOUT": "Sondagem de conteúdo tardio na mesma sessão excedeu o tempo limite",
    "SEALED_EVIDENCE_REQUIRED": "Evidência selada necessária",
    "SEARCH_CONFIGURATION_INVALID": "Configuração da inteligência de busca inválida",
    "SEARCH_CRAWLER_BLOCKED": "Crawler de busca bloqueado",
    "SEARCH_QUERIES_REQUIRED": "Termos de busca necessários",
    "SEARCH_TARGET_UNAVAILABLE": "Alvo da inteligência de busca indisponível",
    "SEMANTIC_PREREQUISITE": "Pré-requisito semântico",
    "SEMANTIC_PREREQUISITE_BLOCKED": "Pré-requisito semântico bloqueado",
    "SERP_OBSERVATIONS_NOT_AVAILABLE": "Observações SERP indisponíveis",
    "SITEMAP_ABSENT": "Sitemap ausente",
    "SITEMAP_HTTP_ERROR": "Erro HTTP ao acessar o sitemap",
    "SITEMAP_INVALID": "Sitemap inválido",
    "SITEMAP_NETWORK_ERROR": "Erro de rede ao acessar o sitemap",
    "STRUCTURED_DATA_ABSENT": "Dados estruturados ausentes",
    "STRUCTURED_DATA_ABSENT_NOT_UNIVERSAL_SARI_REQUIREMENT": "Ausência de dados estruturados não é requisito universal do índice de prontidão",
    "STRUCTURED_DATA_NOT_INTERPRETABLE": "Dados estruturados não interpretáveis",
    "STRUCTURED_DATA_TYPE_NOT_IDENTIFIABLE": "Tipo dos dados estruturados não identificável",
    "SUPPORTED_BY_PERSISTED_EVIDENCE": "Suportada pela evidência persistida",
    "SYNTHETIC_LIMITATION": "Limitação da medição sintética",
    "SYNTHETIC_MEASUREMENT": "Medição sintética",
    "TECHNICAL_AI_RETRY_INCOMPLETE": "Nova tentativa da IA técnica incompleta",
    "TEMPORAL_ASSOCIATION_ONLY": "Somente associação temporal",
    "TITLE_MISSING": "Título ausente",
    "UNEXPECTED_BROWSER_RESULT": "Resultado inesperado do navegador",
    "UNKNOWN_PERIOD": "Período não determinado",
    "URL_REPUTATION_REQUIRES_EXPLICIT_PRIVACY_AND_PROVIDER_POLICY": "Consulta de reputação de URL exige política explícita de privacidade e provedor",
})

# Known metric identifiers and Chromium network diagnostics only. Do not
# register ISO country abbreviations globally: that would change pt-BR tags.
PUBLIC_VALUE_LABELS.update({
    "LCP": "LCP",
    "INP": "INP",
    "CLS": "CLS",
    "ERR_ABORTED": "Requisição interrompida pelo navegador",
})

PUBLIC_PHRASE_LABELS: dict[str, str] = {
    "external organic result; business equivalence is not inferred": "Resultado orgânico externo; equivalência comercial não é inferida",
    "public-authority domain heuristic": "Heurística de domínio de autoridade pública",
}

def _key(value: Any) -> str:
    raw = str(value or "").strip().upper()
    return re.sub(r"[^A-Z0-9]+", "_", raw).strip("_")

def public_label(value: Any) -> str | None:
    raw = str(value or "").strip()
    if not raw:
        return None
    phrase = PUBLIC_PHRASE_LABELS.get(raw.casefold())
    return phrase or PUBLIC_VALUE_LABELS.get(_key(raw)) or supplemental_public_label(raw)

_PUBLIC_SINGLE_TOKEN_PATTERN = "|".join(
    re.escape(key)
    for key in sorted(
        (key for key in PUBLIC_VALUE_LABELS if "_" not in key),
        key=len,
        reverse=True,
    )
)
_PUBLIC_TOKEN_RE = re.compile(
    rf"\b(?:{_PUBLIC_SINGLE_TOKEN_PATTERN}|[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+)\b"
)

def public_text(value: Any) -> str:
    """Translate known internal tokens embedded in human-facing diagnostic text."""
    raw = str(value or "")
    if not raw:
        return raw
    # Replace the whole known browser event; otherwise the obsolete net::
    # namespace would prefix a human-readable sentence in the HTML.
    raw = re.sub(
        r"\bnet::ERR_ABORTED\b",
        "Requisição interrompida pelo navegador",
        raw,
        flags=re.IGNORECASE,
    )
    return _PUBLIC_TOKEN_RE.sub(
        lambda match: public_label(match.group(0)) or safe_visible_fallback(match.group(0)),
        raw,
    )

def public_contract_label(value: Any) -> str:
    raw = str(value or "").strip()
    if not raw:
        return "-"
    parts = raw.split(":")
    head = _key(parts[0])

    if head == "DIMENSION_NOT_APPLICABLE" and len(parts) >= 2:
        return f"Dimensão {public_label(parts[1]) or parts[1].replace('_',' ').title()} não aplicável"
    if head == "DIMENSION_MEASUREMENT_LIMITED" and len(parts) >= 2:
        return f"Medição limitada na dimensão {public_label(parts[1]) or parts[1].replace('_',' ').title()}"
    if head == "DIMENSION_NOT_CONSOLIDATED" and len(parts) >= 2:
        return f"Dimensão {public_label(parts[1]) or parts[1].replace('_',' ').title()} ainda não consolidada"
    if head == "CRITICAL_GATE" and len(parts) >= 3:
        subject = {
            "DISCOVERY": "descoberta",
            "INDEXABILITY": "indexabilidade",
            "EXTRACTION": "extração",
        }.get(_key(parts[1]), parts[1].replace("_"," ").casefold())
        state = {
            "WARNING": "atenção",
            "PASS": "aprovado",
            "FAIL": "não aprovado",
            "BLOCKED": "bloqueado",
            "UNKNOWN": "não determinado",
            "NOT_DETERMINABLE": "não determinável",
            "NOT_APPLICABLE": "não aplicável",
        }.get(_key(parts[2]), public_label(parts[2]) or parts[2].replace("_"," ").casefold())
        return f"Gate crítico de {subject}: {state}"
    if head == "READINESS_STATUS" and len(parts) >= 2:
        state = {
            "ATTENTION": "atenção",
            "READY": "pronto",
            "BLOCKED": "bloqueado",
            "UNKNOWN": "não determinado",
            "NOT_DETERMINABLE": "não determinável",
        }.get(_key(parts[1]), public_label(parts[1]) or parts[1].replace("_"," ").casefold())
        return f"Estado de prontidão: {state}"
    if head == "OVERALL_MEASUREMENT_BELOW_MINIMUM_GATE":
        return "Medição geral abaixo do mínimo exigido"
    if head == "OVERALL_MEASUREMENT_BELOW_CONSOLIDATION_GATE":
        return "Medição geral abaixo do mínimo para consolidação"
    if head == "OVERALL_AGGREGATION":
        return "Agregação Hierárquica Ponderada de Prontidão - versão pública 001"
    if head == "DIMENSION_WEIGHTS":
        return "Pesos das Dimensões do Índice de Prontidão - versão pública 001"
    if head == "GROUP_WEIGHTS":
        return "Pesos dos Grupos do Índice de Prontidão - versão pública 001"
    if head == "CRITICAL_GATES":
        return "Critérios Críticos de Prontidão - versão pública 001"
    if head == "MEASUREMENT_CONFIDENCE":
        return "Modelo de Confiança da Medição - versão pública 001"
    if head == "EXTERNAL_CRAWL_CORROBORATION":
        rule = parts[1] if len(parts) > 1 else "BR-GEO-060"
        return f"Corroboração externa de crawl: somente impacto positivo, limite geral 0,45 - regra {rule}"
    if head == "EMPIRICAL_VALIDATION":
        return "Validação empírica: não participa da pontuação"

    return public_label(raw) or raw.replace("_", " ")

__all__ = ["PUBLIC_VALUE_LABELS", "PUBLIC_PHRASE_LABELS", "public_label", "public_text", "public_contract_label"]
