import React from 'react';
import { Routes, Route, useLocation } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Building2, CircleDollarSign, Gauge, KeyRound, LayoutDashboard, ScrollText, Settings2, ShieldCheck, UsersRound, AlertTriangle, TrendingUp, LockKeyhole, SlidersHorizontal, UserRoundSearch } from 'lucide-react';
import { mockSaas } from '@rasai/prototype-mocks';
import { AppShell, Button, Callout, ContextPill, MetricCard, PageHeader, Panel, SimpleTable, StatusBadge, TrendChart } from '@rasai/prototype-ui';

const nav = [
 {label:'Visão geral',href:'/',icon:<LayoutDashboard size={17}/>},
 {label:'Clientes',href:'/clients',icon:<Building2 size={17}/>},
 {label:'Usuários',href:'/users',icon:<UsersRound size={17}/>},
 {label:'Consumo & custos',href:'/usage',icon:<CircleDollarSign size={17}/>,badge:'live'},
 {label:'Credenciais',href:'/credentials',icon:<KeyRound size={17}/>},
 {label:'Defaults globais',href:'/defaults',icon:<SlidersHorizontal size={17}/>},
 {label:'Auditoria',href:'/audit-trail',icon:<ScrollText size={17}/>},
];
function OwnerChip(){return <div className="owner-chip"><div className="owner-avatar">JC</div><div><strong>Platform Owner</strong><span>RASAi Backoffice</span></div></div>}
function Context(){return <><ContextPill label="Escopo" value="Plataforma inteira"/><ContextPill label="Região" value="Global"/><ContextPill label="Modo" value="Proprietário"/></>}

function Overview(){ const clients=useQuery({queryKey:['bo-clients'],queryFn:()=>mockSaas.clients()}); const usage=useQuery({queryKey:['bo-usage'],queryFn:()=>mockSaas.usage(),refetchInterval:5000}); const credentials=useQuery({queryKey:['bo-creds'],queryFn:()=>mockSaas.platformCredentials()}); const c=clients.data??[]; const u=usage.data??[]; const platformCost=u.reduce((s,x)=>s+x.platformCost,0); const billable=u.reduce((s,x)=>s+x.billableCost,0); const byok=u.filter(x=>x.credentialSource==='USER_PRIVATE').length; return <><PageHeader eyebrow="Platform owner" title="Backoffice RASAi" description="Controle global de clientes, consumo, custos, credenciais compartilhadas, defaults e trilha administrativa."/><div className="grid metrics"><MetricCard label="Clientes ativos" value={String(c.filter(x=>x.status==='ACTIVE').length)} tone="positive" hint={`${c.reduce((s,x)=>s+x.users,0)} usuários no total`}/><MetricCard label="Custo plataforma" value={`US$ ${platformCost.toFixed(2)}`} tone="warning" hint="Somente credenciais pagas pelo RASAi"/><MetricCard label="Billable" value={`US$ ${billable.toFixed(2)}`} tone="info" hint="Atribuição mock, não faturamento real"/><MetricCard label="Chamadas BYOK" value={String(byok)} tone="positive" hint="Registradas com custo plataforma = 0"/></div><div className="grid two"><Panel title="Custo de plataforma" subtitle="Série demonstrativa para validação visual"><TrendChart values={[31,42,39,58,64,71]} labels={['Ago 1','Ago 8','Ago 15','Ago 22','Set 1','Hoje']} name="US$"/></Panel><Panel title="Saúde operacional"><div className="kpi-line"><span>Credenciais compartilhadas</span><strong>{credentials.data?.length??0}</strong></div><div className="kpi-line"><span>Providers degradados</span><strong>{credentials.data?.filter(x=>x.status==='DEGRADED').length??0}</strong></div><div className="kpi-line"><span>Jobs ativos clientes</span><strong>{c.reduce((s,x)=>s+x.activeJobs,0)}</strong></div><div className="kpi-line"><span>Eventos observados</span><strong>{u.length}</strong></div><Callout title="Atribuição financeira">BYOK permanece no histórico com provider cost estimado, mas `platform_cost` e `billable_cost` ficam zerados para o consumo da credencial própria.</Callout></Panel></div><Panel title="Clientes com maior consumo" subtitle="A visão real virá do usage ledger do SaaS" className="stack" ><SimpleTable columns={[{key:'name',label:'Cliente'},{key:'plan',label:'Plano'},{key:'users',label:'Usuários'},{key:'projects',label:'Projetos'},{key:'activeJobs',label:'Jobs ativos'},{key:'monthlyPlatformCost',label:'Custo plataforma',render:r=><span className="money cost">US$ {r.monthlyPlatformCost.toFixed(2)}</span>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>}]} rows={c}/></Panel></>; }

function Clients(){ const {data=[]}=useQuery({queryKey:['clients'],queryFn:()=>mockSaas.clients()}); return <><PageHeader eyebrow="Tenants" title="Clientes" description="Visão administrativa global; esta superfície não pertence à tenancy normal da aplicação do cliente." actions={<Button variant="secondary">Exportar visão</Button>}/><Panel title="Organizações"><SimpleTable columns={[{key:'name',label:'Cliente'},{key:'organizationId',label:'ID'},{key:'plan',label:'Plano'},{key:'users',label:'Usuários'},{key:'projects',label:'Projetos'},{key:'activeJobs',label:'Jobs ativos'},{key:'monthlyPlatformCost',label:'Custo mês',render:r=><span className="money">US$ {r.monthlyPlatformCost.toFixed(2)}</span>},{key:'monthlyBillable',label:'Billable',render:r=><span className="money">US$ {r.monthlyBillable.toFixed(2)}</span>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>}]} rows={data}/></Panel></>; }

const users=[
 {id:'USR-ANA',name:'Ana Martins',org:'ACME Digital',role:'ANALYST',jobs:14,calls:417,cost:0,status:'ACTIVE'},
 {id:'USR-LUCAS',name:'Lucas Reis',org:'Nova Seguros',role:'ADMIN',jobs:22,calls:688,cost:42.18,status:'ACTIVE'},
 {id:'USR-BIA',name:'Beatriz Lima',org:'Grupo Varejo',role:'OPERATOR',jobs:9,calls:203,cost:18.91,status:'ACTIVE'},
 {id:'USR-MARINA',name:'Marina Lopes',org:'ACME Digital',role:'VIEWER',jobs:0,calls:0,cost:0,status:'ACTIVE'},
];
function Users(){return <><PageHeader eyebrow="Identity" title="Usuários" description="Consulta administrativa de usuários clientes, tenancy e consumo atribuído."/><Panel title="Usuários"><SimpleTable columns={[{key:'name',label:'Usuário'},{key:'org',label:'Organização'},{key:'role',label:'Role'},{key:'jobs',label:'Jobs'},{key:'calls',label:'Calls'},{key:'cost',label:'Custo SaaS',render:r=><span className={`money ${r.cost===0?'zero':'cost'}`}>US$ {r.cost.toFixed(2)}</span>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>}]} rows={users}/></Panel></>}

function Usage(){ const {data=[]}=useQuery({queryKey:['usage'],queryFn:()=>mockSaas.usage(),refetchInterval:5000}); const provider=data.reduce((s,x)=>s+x.providerCostEstimate,0), platform=data.reduce((s,x)=>s+x.platformCost,0), billable=data.reduce((s,x)=>s+x.billableCost,0); return <><PageHeader eyebrow="FinOps" title="Consumo & custos" description="Rastreabilidade do consumo até tenant, usuário, job, audit, report e credencial lógica."/><div className="grid metrics"><MetricCard label="Provider cost" value={`US$ ${provider.toFixed(3)}`} tone="info"/><MetricCard label="Platform cost" value={`US$ ${platform.toFixed(3)}`} tone="warning"/><MetricCard label="Billable cost" value={`US$ ${billable.toFixed(3)}`} tone="positive"/><MetricCard label="Eventos" value={String(data.length)}/></div><div className="filter-strip"><button className="filter-chip">Período · hoje</button><button className="filter-chip">Cliente · todos</button><button className="filter-chip">Provider · todos</button><button className="filter-chip">Credencial · todas</button><button className="filter-chip">Status · todos</button></div><Panel title="Ledger de consumo" subtitle="Nenhum segredo é armazenado na superfície de analytics"><SimpleTable columns={[{key:'occurredAt',label:'Quando',render:r=>new Date(r.occurredAt).toLocaleTimeString('pt-BR')},{key:'organizationName',label:'Cliente'},{key:'userName',label:'Usuário'},{key:'provider',label:'Provider'},{key:'operation',label:'Operação'},{key:'credentialSource',label:'Origem'},{key:'credentialId',label:'Credencial'},{key:'providerCostEstimate',label:'Provider',render:r=><span className="money">${r.providerCostEstimate.toFixed(3)}</span>},{key:'platformCost',label:'RASAi',render:r=><span className={`money ${r.platformCost===0?'zero':'cost'}`}>${r.platformCost.toFixed(3)}</span>},{key:'billableCost',label:'Billable',render:r=><span className={`money ${r.billableCost===0?'zero':''}`}>${r.billableCost.toFixed(3)}</span>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>}]} rows={data}/></Panel></>; }

function Credentials(){ const {data=[]}=useQuery({queryKey:['platform-creds'],queryFn:()=>mockSaas.platformCredentials()}); return <><PageHeader eyebrow="Secrets governance" title="Credenciais compartilhadas" description="O proprietário gerencia credenciais da plataforma. Clientes recebem direito de uso, nunca o secret." actions={<Button><KeyRound size={14}/> Nova credencial</Button>}/><Callout title="Fronteira de segurança">O frontend recebe somente referência lógica, provider, owner, saúde e metadados. A credencial real permanece exclusivamente no backend/secret store.</Callout><div className="grid two" style={{marginTop:16}}>{data.map(c=><div className="credential-card" key={c.credentialId}><header><div><h3>{c.label}</h3><p>{c.provider} · <span className="scope-chip">{c.credentialId}</span></p></div><StatusBadge status={c.status}/></header><div className="cost-split"><div className="cost-box"><span>Consumidores</span><strong>{c.consumers??0}</strong></div><div className="cost-box"><span>Último uso</span><strong>{c.lastUsedAt?new Date(c.lastUsedAt).toLocaleTimeString('pt-BR'):'—'}</strong></div><div className="cost-box"><span>Origem</span><strong>PLATFORM</strong></div></div><div className="split" style={{marginTop:12}}><span className="subtle"><LockKeyhole size={12} style={{verticalAlign:'middle'}}/> segredo não recuperável</span><Button variant="secondary">Gerenciar</Button></div></div>)}</div></>; }

function Defaults(){ const {data=[]}=useQuery({queryKey:['defaults'],queryFn:()=>mockSaas.platformDefaults()}); return <><PageHeader eyebrow="Policy" title="Defaults globais" description="Valores padrão publicados pelo proprietário e herdados pelos clientes, respeitando escopos de override definidos no futuro contrato SaaS." actions={<Button><Settings2 size={14}/> Publicar versão</Button>}/><Callout title="Compatibilidade com o console">Esses defaults não substituem o `default.ini` nem tornam o console dependente do SaaS. Na Web, tornam-se política distribuída e versionada; no console local, continuam existindo defaults locais.</Callout><Panel title="Configurações publicadas" subtitle="A UI mostra nomes humanos e mantém o identificador técnico para rastreabilidade"><div>{data.map(d=><div className="default-row" key={d.key}><div><strong>{d.label}</strong><span className="mono" style={{display:'block'}}>{d.key}</span></div><strong>{String(d.value)}</strong><span>{d.category}<br/>{d.scopeLabel}</span><Button variant="secondary">Editar</Button></div>)}</div></Panel></>; }

const auditEvents=[
 {when:'13/09 22:41',actor:'Platform Owner',action:'Atualizou política de preços IA',target:'AI-PRICING-2026-09'},
 {when:'13/09 21:18',actor:'Platform Owner',action:'Substituiu credencial OpenAI compartilhada',target:'CRD-PLAT-OPENAI-01'},
 {when:'13/09 20:52',actor:'Admin · Nova Seguros',action:'Criou usuário e membership',target:'USR-LUCAS-02'},
 {when:'13/09 19:07',actor:'Scheduler',action:'Materializou ocorrência de schedule',target:'SCH-1001 → JOB-01982'},
 {when:'13/09 18:31',actor:'Ana Martins',action:'Usou credencial privada OpenAI',target:'CRD-USER-OPENAI · AUD-20260913-004'},
];
function AuditTrail(){return <><PageHeader eyebrow="Governança" title="Trilha de auditoria" description="Histórico de ações administrativas e eventos relevantes de governança; valores de secrets nunca aparecem."/><Panel title="Eventos"><div>{auditEvents.map((e,i)=><div className="audit-event" key={i}><time>{e.when}</time><strong>{e.actor}</strong><div>{e.action}</div><span className="mono">{e.target}</span></div>)}</div></Panel></>}

export default function App(){ const location=useLocation(); return <AppShell brand="RASAi Backoffice" subtitle="Platform control" nav={nav} activePath={location.pathname} topRight={<OwnerChip/>} context={<Context/>}><Routes><Route path="/" element={<Overview/>}/><Route path="/clients" element={<Clients/>}/><Route path="/users" element={<Users/>}/><Route path="/usage" element={<Usage/>}/><Route path="/credentials" element={<Credentials/>}/><Route path="/defaults" element={<Defaults/>}/><Route path="/audit-trail" element={<AuditTrail/>}/></Routes></AppShell>; }
